# Dullahan Project Configuration

# Cloud Settings
cloud:
  url: "https://7pyzcafao6.execute-api.ca-central-1.amazonaws.com"
  # api_key:

# Tracker Settings
trackers:
  - name: "Tracker 1"
    port: 8000
  - name: "Tracker 2"
    port: 8001

# Orchestrator Settings
orchestrator:
  port: 3000

# Proxy Settings
proxy:
  port: 3001

# Video Sources
# This section can be used to override the existing 'apps/tracker/config.yaml'
# Leave empty by default
video_sources: []

# Proxy Cache Settings
proxy_cache:
  enabled: true
  check_interval: 300 # Network check interval in seconds

# Observation Types
observation_types:
  - "crowd"
  - "doors"
  - "views"
  - "waiting_time"
  - "objects"
